#!/bin/bash
set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project paths
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WEBGAL_DIR="$PROJECT_ROOT/WebGAL"
GAME_DIR="$PROJECT_ROOT/game"
SCRIPTS_SOURCE="/Users/jordantian/Documents/hacknation/output/one_night_four_friends/scripts"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  One Night, Four Friends - WebGAL Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check prerequisites
echo -e "${YELLOW}[1/8]${NC} Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}✗ Node.js is not installed${NC}"
    echo "Please install Node.js 18+ from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}✗ Node.js version is too old (need 18+, have $(node -v))${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}✗ Python 3 is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Python $(python3 --version)${NC}"

# Check git
if ! command -v git &> /dev/null; then
    echo -e "${RED}✗ Git is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Git $(git --version | cut -d' ' -f3)${NC}"
echo ""

# Clone WebGAL if not exists
echo -e "${YELLOW}[2/8]${NC} Setting up WebGAL engine..."

if [ -d "$WEBGAL_DIR" ]; then
    echo -e "${BLUE}WebGAL directory exists. Pulling latest changes...${NC}"
    cd "$WEBGAL_DIR"
    git pull origin main || git pull origin master || echo "Could not pull updates, using existing version"
else
    echo -e "${BLUE}Cloning WebGAL from GitHub...${NC}"
    git clone https://github.com/MakinoharaShoko/WebGAL.git "$WEBGAL_DIR"
fi

echo -e "${GREEN}✓ WebGAL engine ready${NC}"
echo ""

# Install WebGAL dependencies
echo -e "${YELLOW}[3/8]${NC} Installing WebGAL dependencies..."
cd "$WEBGAL_DIR/packages/webgal"

if [ -f "package.json" ]; then
    npm install --legacy-peer-deps
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${RED}✗ Could not find WebGAL package.json${NC}"
    echo "The WebGAL repository structure may have changed."
    echo "Please check: $WEBGAL_DIR/packages/webgal"
    exit 1
fi
echo ""

# Generate placeholder assets
echo -e "${YELLOW}[4/8]${NC} Generating placeholder assets..."
cd "$PROJECT_ROOT"
python3 scripts/generate_placeholders.py

echo -e "${GREEN}✓ Placeholder assets generated${NC}"
echo ""

# Copy game scripts
echo -e "${YELLOW}[5/8]${NC} Copying game scripts..."

if [ -d "$SCRIPTS_SOURCE" ]; then
    cp -v "$SCRIPTS_SOURCE"/*.txt "$GAME_DIR/scene/" 2>/dev/null || echo "No .txt files found in source"
    echo -e "${GREEN}✓ Game scripts copied${NC}"
else
    echo -e "${YELLOW}⚠ Scripts source directory not found: $SCRIPTS_SOURCE${NC}"
    echo "You'll need to manually copy your .txt files to: $GAME_DIR/scene/"
fi
echo ""

# Create start.txt if it doesn't exist
if [ ! -f "$GAME_DIR/scene/start.txt" ]; then
    echo -e "${YELLOW}[6/8]${NC} Creating start.txt entry point..."
    cat > "$GAME_DIR/scene/start.txt" << 'EOF'
// One Night, Four Friends - Entry Point
// Auto-generated by setup script

start:
  // Game starts with the briefing
  jump:briefing;
EOF
    echo -e "${GREEN}✓ start.txt created${NC}"
else
    echo -e "${YELLOW}[6/8]${NC} start.txt already exists, skipping..."
fi
echo ""

# Create symbolic link or copy game assets to WebGAL public directory
echo -e "${YELLOW}[7/8]${NC} Linking game assets to WebGAL..."

WEBGAL_PUBLIC="$WEBGAL_DIR/packages/webgal/public/game"
WEBGAL_GAMES="$WEBGAL_DIR/packages/webgal/public/games"

# Create the appropriate directory structure
if [ -d "$WEBGAL_PUBLIC" ]; then
    TARGET_DIR="$WEBGAL_PUBLIC"
elif [ -d "$WEBGAL_GAMES" ]; then
    TARGET_DIR="$WEBGAL_GAMES/one_night_four_friends"
    mkdir -p "$TARGET_DIR"
else
    # Create the standard location
    TARGET_DIR="$WEBGAL_DIR/packages/webgal/public/game"
    mkdir -p "$TARGET_DIR"
fi

# Copy game content
echo "Copying game assets to: $TARGET_DIR"
cp -R "$GAME_DIR"/* "$TARGET_DIR/"

echo -e "${GREEN}✓ Game assets linked${NC}"
echo ""

# Create launch script
echo -e "${YELLOW}[8/8]${NC} Creating launch script..."

cat > "$PROJECT_ROOT/launch.sh" << 'LAUNCH_EOF'
#!/bin/bash
# Quick launch script for One Night, Four Friends

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WEBGAL_DIR="$PROJECT_ROOT/WebGAL/packages/webgal"

echo "Starting WebGAL development server..."
echo "Game will be available at: http://localhost:5173"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

cd "$WEBGAL_DIR"
npm run dev
LAUNCH_EOF

chmod +x "$PROJECT_ROOT/launch.sh"

echo -e "${GREEN}✓ Launch script created${NC}"
echo ""

# Success message
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "To start your game:"
echo -e "  ${BLUE}cd $PROJECT_ROOT${NC}"
echo -e "  ${BLUE}./launch.sh${NC}"
echo ""
echo -e "Or manually:"
echo -e "  ${BLUE}cd WebGAL/packages/webgal${NC}"
echo -e "  ${BLUE}npm run dev${NC}"
echo ""
echo -e "Game will be available at: ${GREEN}http://localhost:5173${NC}"
echo ""
echo -e "For more information, see: ${BLUE}QUICKSTART.md${NC}"
echo ""
